// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkbhdmpalgurcctylemv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYmhkbXBhbGd1cmNjdHlsZW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODMxNTYsImV4cCI6MjA2OTE1OTE1Nn0.6k2hRb6rrjHj4tc-yNWNsi0v7Hxk6modx8dt1Gls2wI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});